apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.base.name }}
  namespace: {{ .Values.base.namespace }}
  labels:
    app: {{ .Values.base.name }}
spec:
  replicas: {{ .Values.base.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.base.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.base.name }}
    spec:
      serviceAccountName: myinspect-sa
      nodeName: vm-0-16-centos
      containers:
        - name: {{ .Values.base.name }}
          image: "{{ .Values.base.image }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: "Release"
              value: "1"
          workingDir: "/app"
          command: [ "./myinspectoperator" ]
          {{- if .Values.service.ports }}
          ports:
            {{- range .Values.service.ports }}
            - name: port-80
              containerPort: 80
              protocol: TCP
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}